=== UO261072/SEW/equipamientos.dtd
<!ELEMENT equipamientos (equipamiento+)>
<!ELEMENT equipamiento (nivel, clase, armas, armaduras)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT clase (#PCDATA)>
<!ELEMENT armas (primaria?,secundaria?)>
<!ELEMENT armaduras (casco?,pecho?,brazoIz?,brazoDer?,piernas?)>
<!ELEMENT primaria (aumentos)>
<!ELEMENT secundaria (aumentos)>
<!ELEMENT casco (aumentos)>
<!ELEMENT pecho (aumentos)>
<!ELEMENT brazoIz (aumentos)>
<!ELEMENT brazoDer (aumentos)>
<!ELEMENT piernas (aumentos)>
<!ELEMENT aumentos (aumento*)>
<!ELEMENT aumento (#PCDATA)>
<!ATTLIST clase 
	nivel CDATA #REQUIRED>
<!ATTLIST primaria 
	nombre CDATA #REQUIRED
	tipo CDATA #REQUIRED
	fabricante CDATA #REQUIRED
	ataque CDATA #REQUIRED>
<!ATTLIST secundaria 
	nombre CDATA #REQUIRED
	tipo CDATA #REQUIRED
	fabricante CDATA #REQUIRED
	ataque CDATA #REQUIRED>
<!ATTLIST aumentos 
	huecos CDATA #REQUIRED>
<!ATTLIST casco 
	nombre CDATA #REQUIRED
	defensa CDATA #REQUIRED>
<!ATTLIST pecho 
	nombre CDATA #REQUIRED
	defensa CDATA #REQUIRED>
<!ATTLIST brazoIz 
	nombre CDATA #REQUIRED
	defensa CDATA #REQUIRED>
<!ATTLIST brazoDer 
	nombre CDATA #REQUIRED
	defensa CDATA #REQUIRED>
<!ATTLIST piernas 
	nombre CDATA #REQUIRED
	defensa CDATA #REQUIRED>

=== UO261072/SEW/equipamientos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipamientos SYSTEM "equipamientos.dtd">
<equipamientos>
	<equipamiento>
		<nivel>35</nivel>
		<clase nivel="8">Drifter</clase>
		<armas>
			<primaria nombre="Espada sagrada" tipo="Espada corta" fabricante="Sakura Logistics" ataque="10">
				<aumentos huecos="3">
					<aumento>Potencia+</aumento>
					<aumento>Curacion+</aumento>
					<aumento>Ataque++</aumento>
				</aumentos>
			</primaria>
			<secundaria nombre="Railgun gravitatoria" tipo="Railgun" fabricante="Man'on Corp." ataque="20">
				<aumentos huecos="2">
					<aumento>Potencia+</aumento>
					<aumento>Curacion+</aumento>
				</aumentos>
			</secundaria>
		</armas>
		<armaduras>
			<casco nombre="Casco 1" defensa="10">
				<aumentos huecos="3">
					<aumento>Potencia+</aumento>
					<aumento>Curacion+</aumento>
					<aumento>Ataque++</aumento>
				</aumentos>
			</casco>
			<pecho nombre="Pecho 1" defensa="10">
				<aumentos huecos="3">
					<aumento>Defensa Especial++</aumento>
					<aumento>TP++</aumento>
					<aumento>TP++</aumento>
				</aumentos>
			</pecho>
			<brazoIz nombre="Brazo Izquierdo 1" defensa="10">
				<aumentos huecos="2">
					<aumento>Curacion+</aumento>
				</aumentos>
			</brazoIz>
			<brazoDer nombre="Brazo Derecho 1" defensa="10">
				<aumentos huecos="3">
					<aumento>Gravedad++</aumento>
					<aumento>Fisico</aumento>
					<aumento>Enfriamiento++</aumento>
				</aumentos>
			</brazoDer>
			<piernas nombre="Piernas 1" defensa="10">
				<aumentos huecos="1">
				</aumentos>
			</piernas>
		</armaduras>
	</equipamiento>
</equipamientos>
